### ISSUE TITLE
Uhrzeit anzeige 

### ISSUE THREAD

**Issue by Lenade** [jonasfischer/admuc_spots#8]
Uhrzeiten werden um 12 Stunden verschoben angezeigt
14:00 wird als 02:00 angezeigt
10:00 wird als 22:00 angezeigt
vorangehende 0 werden abgeschnitten 
14:5

**Comment by jonasfischer** [comment]
Erledigt für EventList (bzw. EventsAdapter) und EventListDetail. Vorgehen bei Datendarstellung bitte analog zu diesen beiden Stellen.
